name: Push trigger for aws-integration
on:
  pull_request:
    branches:
      - integration

jobs:
  build:
    name: Dispatch to `aws-integration` to plan
    runs-on: ubuntu-latest
    steps:
      - name: aws-integration-plan
        uses: convictional/trigger-workflow-and-wait@v1.0.1
        with:
          owner: daringway
          repo: aws-integration
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          event_type: module_plan
