name: Push trigger for aws-integration
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Dispatch to `aws-integration`
    runs-on: ubuntu-latest
    steps:
      - name: aws-integration
        uses: daringway/trigger-workflow-and-wait@comments
        with:
          owner: daringway
          repo: aws-integration
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          event_type: push_trigger

