name: Push trigger for aws-integration
on:
  push:
    branches:
      - integration

jobs:
  build:
    name: Dispatch to `aws-integration`
    runs-on: ubuntu-latest
    steps:
      - name: Emit repository_dispatch
        uses: mvasigh/dispatch-action@master
        with:
          # You should create a personal access token and store it in your repository
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repo: aws-integration
          owner: daringway
          event_type: push_trigger
          
